/**
 * Comprehensive ISO-3166 country dataset used by the application form.
 *
 * Bundled locally (rather than fetched from a runtime API) so the form works
 * offline, has no network latency on a static list, and never breaks if a
 * third-party countries API is rate-limited or down. Each entry carries the
 * ISO-2 code, international dialing code and a demonym (nationality), which is
 * everything the searchable country/phone dropdowns need.
 */
export interface Country {
  /** Common country name */
  name: string;
  /** ISO-3166-1 alpha-2 code (also used to derive the flag emoji) */
  code: string;
  /** International dialing / calling code, including the leading "+" */
  dialCode: string;
  /** Demonym (nationality), e.g. "French" for France */
  nationality: string;
}

export const COUNTRY_DATA: Country[] = [
  { name: 'Afghanistan', code: 'AF', dialCode: '+93', nationality: 'Afghan' },
  { name: 'Albania', code: 'AL', dialCode: '+355', nationality: 'Albanian' },
  { name: 'Algeria', code: 'DZ', dialCode: '+213', nationality: 'Algerian' },
  { name: 'Andorra', code: 'AD', dialCode: '+376', nationality: 'Andorran' },
  { name: 'Angola', code: 'AO', dialCode: '+244', nationality: 'Angolan' },
  { name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1268', nationality: 'Antiguan' },
  { name: 'Argentina', code: 'AR', dialCode: '+54', nationality: 'Argentine' },
  { name: 'Armenia', code: 'AM', dialCode: '+374', nationality: 'Armenian' },
  { name: 'Australia', code: 'AU', dialCode: '+61', nationality: 'Australian' },
  { name: 'Austria', code: 'AT', dialCode: '+43', nationality: 'Austrian' },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', nationality: 'Azerbaijani' },
  { name: 'Bahamas', code: 'BS', dialCode: '+1242', nationality: 'Bahamian' },
  { name: 'Bahrain', code: 'BH', dialCode: '+973', nationality: 'Bahraini' },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880', nationality: 'Bangladeshi' },
  { name: 'Barbados', code: 'BB', dialCode: '+1246', nationality: 'Barbadian' },
  { name: 'Belarus', code: 'BY', dialCode: '+375', nationality: 'Belarusian' },
  { name: 'Belgium', code: 'BE', dialCode: '+32', nationality: 'Belgian' },
  { name: 'Belize', code: 'BZ', dialCode: '+501', nationality: 'Belizean' },
  { name: 'Benin', code: 'BJ', dialCode: '+229', nationality: 'Beninese' },
  { name: 'Bhutan', code: 'BT', dialCode: '+975', nationality: 'Bhutanese' },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', nationality: 'Bolivian' },
  { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387', nationality: 'Bosnian' },
  { name: 'Botswana', code: 'BW', dialCode: '+267', nationality: 'Botswanan' },
  { name: 'Brazil', code: 'BR', dialCode: '+55', nationality: 'Brazilian' },
  { name: 'Brunei', code: 'BN', dialCode: '+673', nationality: 'Bruneian' },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', nationality: 'Bulgarian' },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226', nationality: 'Burkinabe' },
  { name: 'Burundi', code: 'BI', dialCode: '+257', nationality: 'Burundian' },
  { name: 'Cambodia', code: 'KH', dialCode: '+855', nationality: 'Cambodian' },
  { name: 'Cameroon', code: 'CM', dialCode: '+237', nationality: 'Cameroonian' },
  { name: 'Canada', code: 'CA', dialCode: '+1', nationality: 'Canadian' },
  { name: 'Cape Verde', code: 'CV', dialCode: '+238', nationality: 'Cape Verdean' },
  { name: 'Central African Republic', code: 'CF', dialCode: '+236', nationality: 'Central African' },
  { name: 'Chad', code: 'TD', dialCode: '+235', nationality: 'Chadian' },
  { name: 'Chile', code: 'CL', dialCode: '+56', nationality: 'Chilean' },
  { name: 'China', code: 'CN', dialCode: '+86', nationality: 'Chinese' },
  { name: 'Colombia', code: 'CO', dialCode: '+57', nationality: 'Colombian' },
  { name: 'Comoros', code: 'KM', dialCode: '+269', nationality: 'Comoran' },
  { name: 'Congo (Brazzaville)', code: 'CG', dialCode: '+242', nationality: 'Congolese' },
  { name: 'Congo (Kinshasa)', code: 'CD', dialCode: '+243', nationality: 'Congolese' },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', nationality: 'Costa Rican' },
  { name: 'Croatia', code: 'HR', dialCode: '+385', nationality: 'Croatian' },
  { name: 'Cuba', code: 'CU', dialCode: '+53', nationality: 'Cuban' },
  { name: 'Cyprus', code: 'CY', dialCode: '+357', nationality: 'Cypriot' },
  { name: 'Czech Republic', code: 'CZ', dialCode: '+420', nationality: 'Czech' },
  { name: 'Denmark', code: 'DK', dialCode: '+45', nationality: 'Danish' },
  { name: 'Djibouti', code: 'DJ', dialCode: '+253', nationality: 'Djiboutian' },
  { name: 'Dominica', code: 'DM', dialCode: '+1767', nationality: 'Dominican' },
  { name: 'Dominican Republic', code: 'DO', dialCode: '+1809', nationality: 'Dominican' },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', nationality: 'Ecuadorian' },
  { name: 'Egypt', code: 'EG', dialCode: '+20', nationality: 'Egyptian' },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', nationality: 'Salvadoran' },
  { name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240', nationality: 'Equatorial Guinean' },
  { name: 'Eritrea', code: 'ER', dialCode: '+291', nationality: 'Eritrean' },
  { name: 'Estonia', code: 'EE', dialCode: '+372', nationality: 'Estonian' },
  { name: 'Eswatini', code: 'SZ', dialCode: '+268', nationality: 'Swazi' },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251', nationality: 'Ethiopian' },
  { name: 'Fiji', code: 'FJ', dialCode: '+679', nationality: 'Fijian' },
  { name: 'Finland', code: 'FI', dialCode: '+358', nationality: 'Finnish' },
  { name: 'France', code: 'FR', dialCode: '+33', nationality: 'French' },
  { name: 'Gabon', code: 'GA', dialCode: '+241', nationality: 'Gabonese' },
  { name: 'Gambia', code: 'GM', dialCode: '+220', nationality: 'Gambian' },
  { name: 'Georgia', code: 'GE', dialCode: '+995', nationality: 'Georgian' },
  { name: 'Germany', code: 'DE', dialCode: '+49', nationality: 'German' },
  { name: 'Ghana', code: 'GH', dialCode: '+233', nationality: 'Ghanaian' },
  { name: 'Greece', code: 'GR', dialCode: '+30', nationality: 'Greek' },
  { name: 'Grenada', code: 'GD', dialCode: '+1473', nationality: 'Grenadian' },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', nationality: 'Guatemalan' },
  { name: 'Guinea', code: 'GN', dialCode: '+224', nationality: 'Guinean' },
  { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245', nationality: 'Bissau-Guinean' },
  { name: 'Guyana', code: 'GY', dialCode: '+592', nationality: 'Guyanese' },
  { name: 'Haiti', code: 'HT', dialCode: '+509', nationality: 'Haitian' },
  { name: 'Honduras', code: 'HN', dialCode: '+504', nationality: 'Honduran' },
  { name: 'Hungary', code: 'HU', dialCode: '+36', nationality: 'Hungarian' },
  { name: 'Iceland', code: 'IS', dialCode: '+354', nationality: 'Icelandic' },
  { name: 'India', code: 'IN', dialCode: '+91', nationality: 'Indian' },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', nationality: 'Indonesian' },
  { name: 'Iran', code: 'IR', dialCode: '+98', nationality: 'Iranian' },
  { name: 'Iraq', code: 'IQ', dialCode: '+964', nationality: 'Iraqi' },
  { name: 'Ireland', code: 'IE', dialCode: '+353', nationality: 'Irish' },
  { name: 'Israel', code: 'IL', dialCode: '+972', nationality: 'Israeli' },
  { name: 'Italy', code: 'IT', dialCode: '+39', nationality: 'Italian' },
  { name: 'Ivory Coast', code: 'CI', dialCode: '+225', nationality: 'Ivorian' },
  { name: 'Jamaica', code: 'JM', dialCode: '+1876', nationality: 'Jamaican' },
  { name: 'Japan', code: 'JP', dialCode: '+81', nationality: 'Japanese' },
  { name: 'Jordan', code: 'JO', dialCode: '+962', nationality: 'Jordanian' },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', nationality: 'Kazakhstani' },
  { name: 'Kenya', code: 'KE', dialCode: '+254', nationality: 'Kenyan' },
  { name: 'Kiribati', code: 'KI', dialCode: '+686', nationality: 'I-Kiribati' },
  { name: 'Kosovo', code: 'XK', dialCode: '+383', nationality: 'Kosovar' },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', nationality: 'Kuwaiti' },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', nationality: 'Kyrgyzstani' },
  { name: 'Laos', code: 'LA', dialCode: '+856', nationality: 'Laotian' },
  { name: 'Latvia', code: 'LV', dialCode: '+371', nationality: 'Latvian' },
  { name: 'Lebanon', code: 'LB', dialCode: '+961', nationality: 'Lebanese' },
  { name: 'Lesotho', code: 'LS', dialCode: '+266', nationality: 'Basotho' },
  { name: 'Liberia', code: 'LR', dialCode: '+231', nationality: 'Liberian' },
  { name: 'Libya', code: 'LY', dialCode: '+218', nationality: 'Libyan' },
  { name: 'Liechtenstein', code: 'LI', dialCode: '+423', nationality: 'Liechtensteiner' },
  { name: 'Lithuania', code: 'LT', dialCode: '+370', nationality: 'Lithuanian' },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352', nationality: 'Luxembourgish' },
  { name: 'Madagascar', code: 'MG', dialCode: '+261', nationality: 'Malagasy' },
  { name: 'Malawi', code: 'MW', dialCode: '+265', nationality: 'Malawian' },
  { name: 'Malaysia', code: 'MY', dialCode: '+60', nationality: 'Malaysian' },
  { name: 'Maldives', code: 'MV', dialCode: '+960', nationality: 'Maldivian' },
  { name: 'Mali', code: 'ML', dialCode: '+223', nationality: 'Malian' },
  { name: 'Malta', code: 'MT', dialCode: '+356', nationality: 'Maltese' },
  { name: 'Marshall Islands', code: 'MH', dialCode: '+692', nationality: 'Marshallese' },
  { name: 'Mauritania', code: 'MR', dialCode: '+222', nationality: 'Mauritanian' },
  { name: 'Mauritius', code: 'MU', dialCode: '+230', nationality: 'Mauritian' },
  { name: 'Mexico', code: 'MX', dialCode: '+52', nationality: 'Mexican' },
  { name: 'Micronesia', code: 'FM', dialCode: '+691', nationality: 'Micronesian' },
  { name: 'Moldova', code: 'MD', dialCode: '+373', nationality: 'Moldovan' },
  { name: 'Monaco', code: 'MC', dialCode: '+377', nationality: 'Monégasque' },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', nationality: 'Mongolian' },
  { name: 'Montenegro', code: 'ME', dialCode: '+382', nationality: 'Montenegrin' },
  { name: 'Morocco', code: 'MA', dialCode: '+212', nationality: 'Moroccan' },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258', nationality: 'Mozambican' },
  { name: 'Myanmar', code: 'MM', dialCode: '+95', nationality: 'Burmese' },
  { name: 'Namibia', code: 'NA', dialCode: '+264', nationality: 'Namibian' },
  { name: 'Nauru', code: 'NR', dialCode: '+674', nationality: 'Nauruan' },
  { name: 'Nepal', code: 'NP', dialCode: '+977', nationality: 'Nepali' },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', nationality: 'Dutch' },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64', nationality: 'New Zealander' },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', nationality: 'Nicaraguan' },
  { name: 'Niger', code: 'NE', dialCode: '+227', nationality: 'Nigerien' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', nationality: 'Nigerian' },
  { name: 'North Korea', code: 'KP', dialCode: '+850', nationality: 'North Korean' },
  { name: 'North Macedonia', code: 'MK', dialCode: '+389', nationality: 'Macedonian' },
  { name: 'Norway', code: 'NO', dialCode: '+47', nationality: 'Norwegian' },
  { name: 'Oman', code: 'OM', dialCode: '+968', nationality: 'Omani' },
  { name: 'Pakistan', code: 'PK', dialCode: '+92', nationality: 'Pakistani' },
  { name: 'Palau', code: 'PW', dialCode: '+680', nationality: 'Palauan' },
  { name: 'Palestine', code: 'PS', dialCode: '+970', nationality: 'Palestinian' },
  { name: 'Panama', code: 'PA', dialCode: '+507', nationality: 'Panamanian' },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', nationality: 'Papua New Guinean' },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', nationality: 'Paraguayan' },
  { name: 'Peru', code: 'PE', dialCode: '+51', nationality: 'Peruvian' },
  { name: 'Philippines', code: 'PH', dialCode: '+63', nationality: 'Filipino' },
  { name: 'Poland', code: 'PL', dialCode: '+48', nationality: 'Polish' },
  { name: 'Portugal', code: 'PT', dialCode: '+351', nationality: 'Portuguese' },
  { name: 'Qatar', code: 'QA', dialCode: '+974', nationality: 'Qatari' },
  { name: 'Romania', code: 'RO', dialCode: '+40', nationality: 'Romanian' },
  { name: 'Russia', code: 'RU', dialCode: '+7', nationality: 'Russian' },
  { name: 'Rwanda', code: 'RW', dialCode: '+250', nationality: 'Rwandan' },
  { name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1869', nationality: 'Kittitian' },
  { name: 'Saint Lucia', code: 'LC', dialCode: '+1758', nationality: 'Saint Lucian' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', dialCode: '+1784', nationality: 'Vincentian' },
  { name: 'Samoa', code: 'WS', dialCode: '+685', nationality: 'Samoan' },
  { name: 'San Marino', code: 'SM', dialCode: '+378', nationality: 'Sammarinese' },
  { name: 'Sao Tome and Principe', code: 'ST', dialCode: '+239', nationality: 'Sao Tomean' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', nationality: 'Saudi' },
  { name: 'Senegal', code: 'SN', dialCode: '+221', nationality: 'Senegalese' },
  { name: 'Serbia', code: 'RS', dialCode: '+381', nationality: 'Serbian' },
  { name: 'Seychelles', code: 'SC', dialCode: '+248', nationality: 'Seychellois' },
  { name: 'Sierra Leone', code: 'SL', dialCode: '+232', nationality: 'Sierra Leonean' },
  { name: 'Singapore', code: 'SG', dialCode: '+65', nationality: 'Singaporean' },
  { name: 'Slovakia', code: 'SK', dialCode: '+421', nationality: 'Slovak' },
  { name: 'Slovenia', code: 'SI', dialCode: '+386', nationality: 'Slovenian' },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677', nationality: 'Solomon Islander' },
  { name: 'Somalia', code: 'SO', dialCode: '+252', nationality: 'Somali' },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', nationality: 'South African' },
  { name: 'South Korea', code: 'KR', dialCode: '+82', nationality: 'South Korean' },
  { name: 'South Sudan', code: 'SS', dialCode: '+211', nationality: 'South Sudanese' },
  { name: 'Spain', code: 'ES', dialCode: '+34', nationality: 'Spanish' },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', nationality: 'Sri Lankan' },
  { name: 'Sudan', code: 'SD', dialCode: '+249', nationality: 'Sudanese' },
  { name: 'Suriname', code: 'SR', dialCode: '+597', nationality: 'Surinamese' },
  { name: 'Sweden', code: 'SE', dialCode: '+46', nationality: 'Swedish' },
  { name: 'Switzerland', code: 'CH', dialCode: '+41', nationality: 'Swiss' },
  { name: 'Syria', code: 'SY', dialCode: '+963', nationality: 'Syrian' },
  { name: 'Taiwan', code: 'TW', dialCode: '+886', nationality: 'Taiwanese' },
  { name: 'Tajikistan', code: 'TJ', dialCode: '+992', nationality: 'Tajikistani' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', nationality: 'Tanzanian' },
  { name: 'Thailand', code: 'TH', dialCode: '+66', nationality: 'Thai' },
  { name: 'Timor-Leste', code: 'TL', dialCode: '+670', nationality: 'Timorese' },
  { name: 'Togo', code: 'TG', dialCode: '+228', nationality: 'Togolese' },
  { name: 'Tonga', code: 'TO', dialCode: '+676', nationality: 'Tongan' },
  { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1868', nationality: 'Trinidadian' },
  { name: 'Tunisia', code: 'TN', dialCode: '+216', nationality: 'Tunisian' },
  { name: 'Turkey', code: 'TR', dialCode: '+90', nationality: 'Turkish' },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993', nationality: 'Turkmen' },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688', nationality: 'Tuvaluan' },
  { name: 'Uganda', code: 'UG', dialCode: '+256', nationality: 'Ugandan' },
  { name: 'Ukraine', code: 'UA', dialCode: '+380', nationality: 'Ukrainian' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', nationality: 'Emirati' },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', nationality: 'British' },
  { name: 'United States', code: 'US', dialCode: '+1', nationality: 'American' },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', nationality: 'Uruguayan' },
  { name: 'Uzbekistan', code: 'UZ', dialCode: '+998', nationality: 'Uzbekistani' },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', nationality: 'Ni-Vanuatu' },
  { name: 'Vatican City', code: 'VA', dialCode: '+379', nationality: 'Vatican' },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', nationality: 'Venezuelan' },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', nationality: 'Vietnamese' },
  { name: 'Yemen', code: 'YE', dialCode: '+967', nationality: 'Yemeni' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260', nationality: 'Zambian' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263', nationality: 'Zimbabwean' },
];

/**
 * Derive the flag emoji from an ISO-3166-1 alpha-2 code by mapping each letter
 * to its Unicode Regional Indicator Symbol. Avoids storing emoji literals.
 */
export function flagEmoji(code: string): string {
  if (!code || code.length !== 2) return '🏳️';
  const A = 0x1f1e6;
  const base = 'A'.charCodeAt(0);
  return String.fromCodePoint(
    A + (code.toUpperCase().charCodeAt(0) - base),
    A + (code.toUpperCase().charCodeAt(1) - base),
  );
}

/** Sorted list of country names (for the country dropdowns). */
export const COUNTRIES: string[] = COUNTRY_DATA.map((c) => c.name);

/** Sorted, de-duplicated list of demonyms (for the nationality dropdowns). */
export const NATIONALITIES: string[] = Array.from(
  new Set(COUNTRY_DATA.map((c) => c.nationality)),
).sort((a, b) => a.localeCompare(b));
